name: Download Tailscale Install Script
on:
  workflow_dispatch:  # 支持手动点击运行
  push:
    branches: [main]

permissions:
  contents: write  # 必须，允许 Action 提交推送代码

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取当前仓库代码
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. 下载 tailscale install.sh
      - name: Download install.sh
        run: |https://prod-tf-ui.s3.amazonaws.com/s/ff9e491c-49be-4734-803e-a79e6e83dab1/resources/8f1527f7-f188-4655-909a-8199135ac6d8/v1/en-US/CiscoPacketTracer_900_win_64bit.exe?response-cache-control=no-cache&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260505T173047Z&X-Amz-SignedHeaders=host&X-Amz-Credential=AKIAUJZRIEYBD5LJIEBJ%2F20260505%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Expires=30&X-Amz-Signature=b1913dc75676df924a8f89d47bf9e8f45305531ca87f10ccac3fa8448d9ba5e7
          wget -O CiscoPacketTracer_900_win_64bit.exe 

      # 3. 配置 git 身份
      - name: Set git config
        run: |
          git config --local user.name "GitHub Action Bot"
          git config --local user.email "action@github.com"

      # 4. 提交并推回仓库
      - name: Commit & Push
        run: |
          git add CiscoPacketTracer_900_win_64bit.exe
          git commit -m "Auto update install.sh from tailscale.com $(date +'%Y-%m-%d %H:%M:%S')"
          git push
